spring.application.name=garageAPI
# Define cores no terminal
spring.output.ansi.enabled=always
# Define path raiz do endpoint
# http://localhost:8080/garageAPI/algumacoisa
server.servlet.context-path=/garage


spring.profiles.active=test
