spring.application.name=garagem99

# Contexto raiz
server.servlet.context-path=/garagem

# H2 Database
spring.datasource.url=jdbc:h2:mem:garagem
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.defer-datasource-initialization=true

# Console H2 (para visualizar o banco)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console